### ISSUE TITLE
Implement WASTK Paper

### ISSUE THREAD

**Issue by ricardomokhtari** [jakobtorben/Intelligent-public-web-data-extraction#17]
**Goal: Create a working implementation for calculating the weighted abstract syntax tree kernel (WASTK) similarity metric, from https://downloads.hindawi.com/journals/sp/2017/7809047.pdf**

Acceptance criteria:

- Demonstration of calculated scores between parsers

**Comment by namiyousef** [comment]
Helpful sources:
- AST transformations using ast.NodeTransformer and .visit(): https://tobiaskohn.ch/index.php/2018/07/30/transformations-in-python/
- Building interpreter: https://ruslanspivak.com/lsbasi-part7/

Code examples:
- https://gist.github.com/calebmadrigal/0ea93a58cfc7f9d91613aab30d33e20f
