### ISSUE TITLE
Generate similarity baselines using pycode_similar

### ISSUE THREAD

**Issue by ricardomokhtari** [jakobtorben/Intelligent-public-web-data-extraction#18]
**Goal: Calculate similarity scores between parsers using the pycode_similar module and generate plots**

Acceptance criteria:

- Generate heat map or scatter plot of pairwise similarity between the parsers we have written

**Comment by ricardomokhtari** [comment]
Heatmaps computed using pycode_similar

![similarity_matrices](https://user-images.githubusercontent.com/47888468/104837985-08cbe280-58b0-11eb-99a4-8879a892048f.png)

**Comment by ricardomokhtari** [comment]
Heatmaps showing similarity between different parsers computed with pycode_similar. Top set is using the UnifiedDiff() function, bottom set is using the TreeDiff() function

![heatmaps](https://user-images.githubusercontent.com/47888468/105025370-25e5ea00-5a45-11eb-9d55-53172d8c2989.png)

**Comment by acse-jrt3817** [comment]
Interesting, thanks!
It seems like they show the overall same difference but with different scales. The current parser for HSBC and Unilever is identical, except for the argument of the parser. The 98 % for TreeDiff() might represent that you just need to change the argument, which is what we want. Looking at how the different score is produced for this example might inform what the optimal method is for us.  I will try to find out how the zss.distance function in Treediff works.
