### ISSUE TITLE
Plot the parsers (based on their UnifiedDiff/TreeDiff scores)

### ISSUE THREAD

**Issue by namiyousef** [jakobtorben/Intelligent-public-web-data-extraction#19]
Aim to extract information about the usefulness of the parsers: do they give information about the person who wrote them? The company they are from?

**Comment by namiyousef** [comment]
All scatter plots have UnifiedDiff as Feature 0, and TreeDiff as Feature 1.

<img width="265" alt="Screenshot 2021-01-23 at 19 49 51" src="https://user-images.githubusercontent.com/64047828/105611216-3a631300-5db4-11eb-9dc4-e1635a30811c.png">
<img width="261" alt="Screenshot 2021-01-23 at 19 49 58" src="https://user-images.githubusercontent.com/64047828/105611217-3b944000-5db4-11eb-8c54-4f25cb917802.png">
Results in second photo look odd (there seem to be many 'Y' points (?)) -- Update: on closer inspection it seems like many of 'R' points are 1.00 1.00, so they appear to be much less. In this iteration of the plot, 'J' only has three parsers to their name, so the lack of 'J' points not a concern.

**Comment by ricardomokhtari** [comment]
Updated heatmaps now including GSK, Tesco and Shell

![new_heatmaps_unidiff](https://user-images.githubusercontent.com/47888468/105906720-ef4b3900-601b-11eb-9016-4e155167e73d.png)
![new_heatmaps_treediff](https://user-images.githubusercontent.com/47888468/105906722-f07c6600-601b-11eb-89aa-eeaac6cb53fd.png)
