### ISSUE TITLE
Create parsers for Coca Cola

### ISSUE THREAD

**Issue by namiyousef** [jakobtorben/Intelligent-public-web-data-extraction#21]
Website: https://www.coca-colahellenic.com

Success criteria:
- 3 different parsers referring to different website structures (1 current, 2 historical)

**Comment by ricardomokhtari** [comment]
CocaCola blocks crawling - crawled GSK instead

**Comment by namiyousef** [comment]
Issue summary:
- Relevant <div> objects not captured by parser on CocaCola website
