### ISSUE TITLE
Look into the infix method of representing ASTs

### ISSUE THREAD

**Issue by namiyousef** [jakobtorben/Intelligent-public-web-data-extraction#24]
Success criteria:
- create a function that converts an AST to a vectorised form using the 'infix' method
- apply function to at least one parser

**Comment by ricardomokhtari** [comment]
## [Prefix, Infix and Postfix Notation](http://www.cs.man.ac.uk/~pjj/cs212/fix.html)

- These are different ways of writing expressions. "Infix" notation is the way that we are used to writing mathematical formulae, e.g. "(2+1)/5"
- Postfix (also called Reverse Polish Notation (RPN)) is a different notation in which the operators are wirtten after their operands, e.g. (2+1)/5 == 2 1 + 5 / . In postfix notation there is no need for brackets
- Prefix is the opposite of postfix (Polish notation) - the operator comes before the operands (2+1)/5 ==  / + 2 1 5. There is also no need for brackets here
- All of these are different ways of expressing a binary expression tree - there is a great demo [here](https://demonstrations.wolfram.com/PrefixInfixAndPostfixNotation/).
- The interesting thing is that the [postorder tree traversal](https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/) of a binary expression tree produces the postfix representation, which can then be used to obtain the infix expression. This is true also for ASTs - the post order traversal of the AST produces the postfix notation of the tree, from which the infix representation (normal code) can be retrieved. (not entirely sure about this part, may need to read more)
- Additionally, I found that the way to convert an infix expression like (2+1)/5 into a tree is an algorithm called the [Shunting-yard Algorithm](https://en.wikipedia.org/wiki/Shunting-yard_algorithm). I don't know if this is what `ast.parse()` is doing, but this seems to be the standard way.

## How to use this

- We can look into producing the postfix representation of an AST generated with `ast.parse()` by a postorder traversal of the tree. There is an example for doing this [here](https://stackoverflow.com/questions/1339630/algorithm-for-converting-binary-tree-to-post-fix-mathematical-expression).
- We can then find a way to convert the postfix representation to a vector.

## Resources

- https://en.wikipedia.org/wiki/Shunting-yard_algorithm
- https://softwareengineering.stackexchange.com/questions/254074/how-exactly-is-an-abstract-syntax-tree-created/368149
- https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/
- https://tomekkorbak.com/2020/03/25/implementing-shunting-yard-parsing/
- https://stackoverflow.com/questions/42590512/how-to-convert-from-infix-to-postfix-prefix-using-ast-python-module
- https://demonstrations.wolfram.com/PrefixInfixAndPostfixNotation/
