### ISSUE TITLE
Recreate heatmap plots /w and w/o normalization for all parsers

### ISSUE THREAD

**Issue by namiyousef** [jakobtorben/Intelligent-public-web-data-extraction#28]
See issue #19

**Comment by ricardomokhtari** [comment]
Heatmaps with and without normalisation, treediff has been adapted to make it (more) symmetrical. Red boxes show values that were returned as negative, I have displayed the absolute value - this will need fixing.


![normalised](https://user-images.githubusercontent.com/47888468/106742169-90398580-6614-11eb-9a62-92184a0017f3.png)
![non_normalised](https://user-images.githubusercontent.com/47888468/106742175-916ab280-6614-11eb-9d94-ef6b30a8e9b6.png)
